#
# CI for Gateway
#
# This workflow runs tests and other integration tools for the gateway
# application.
#

name: "CI Gateway"

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  #
  # Run pytest
  #
  pytest:
    name: "Python Tests"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osbuild/rpmrepo-ci:latest
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v2
    - name: "Run pytest"
      run: python3 -m pytest src/gateway/*.py
